package com.halaesus.kabasuji.utils;

import java.awt.Color;

import com.halaesus.kabasuji.shared.entity.Piece;
import com.halaesus.kabasuji.shared.entity.PieceSquare;

public class PieceGenerator {

	// TODO: Fix pieces to be placed at TopLeft
	private static PieceSquare pieceSquares[][] = new PieceSquare[][]{
		{	// 1   // (col , row) = (x , y)
			new PieceSquare(0, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
			new PieceSquare(0, 4),
			new PieceSquare(0, 5),
		},
		{	// 2
			new PieceSquare(0, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
			new PieceSquare(0, 4),
			new PieceSquare(1, 0),
		},
		{	// 3
			new PieceSquare(0, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
			new PieceSquare(0, 4),
			new PieceSquare(1, 1),
		},
		{	// 4
			new PieceSquare(0, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
			new PieceSquare(0, 4),
			new PieceSquare(1, 2),
		},
		{	// 5
			new PieceSquare(1, 0),
			new PieceSquare(1, 1),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
			new PieceSquare(0, 4),
		},
		{	// 6
			new PieceSquare(0, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
		},
		{	// 7
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(1, 2),
			new PieceSquare(0, 3),
		},
		{	// 8
			new PieceSquare(0, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
			new PieceSquare(1, 0),
			new PieceSquare(1, 3),
		},
		{	// 9
			new PieceSquare(0, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
		},
		{	// 10
			new PieceSquare(0, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
		},
		{	// 11
			new PieceSquare(0, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
			new PieceSquare(1, 1),
			new PieceSquare(2, 1),
		},
		{	// 12
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
		},
		{	// 13
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(0, 1),
			new PieceSquare(1, 3),
		},
		{	// 14
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(0, 2),
			new PieceSquare(1, 3),
		},
		{	// 15
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(0, 3),
			new PieceSquare(1, 3),
		},
		{	// 16
			new PieceSquare(1, 0),
			new PieceSquare(1, 1),
			new PieceSquare(2, 1),
			new PieceSquare(1, 2),
			new PieceSquare(0, 2),
			new PieceSquare(1, 3),
		},
		{	// 17
			new PieceSquare(1, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
			new PieceSquare(0, 1),
			new PieceSquare(2, 1),
		},
		{	// 18 // 
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
			new PieceSquare(1, 0),
			new PieceSquare(1, 1),
			new PieceSquare(2, 1),
		},
		{	// 19
			new PieceSquare(1, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 3),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
		},
		{	// 20
			new PieceSquare(1, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
			new PieceSquare(0, 4),
		},
		{	// 21
			new PieceSquare(1, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
		},
		{	// 22
			new PieceSquare(1, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(0, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
		},
		{	// 23
			new PieceSquare(0, 1),
			new PieceSquare(1, 1),
			new PieceSquare(2, 1),
			new PieceSquare(2, 0),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
		},
		{	// 24
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(2, 1),
			new PieceSquare(1, 2),
		},
		{	// 25
			new PieceSquare(0, 2),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
			new PieceSquare(1, 1),
			new PieceSquare(2, 1),
			new PieceSquare(2, 0),
		},
		{	// 26
			new PieceSquare(2, 0),
			new PieceSquare(2, 1),
			new PieceSquare(1, 1),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
		},
		{	// 27
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
			new PieceSquare(1, 1),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
		},
		{	// 28
			new PieceSquare(0, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(2, 1),
		},
		{	// 29
			new PieceSquare(0, 0),
			new PieceSquare(0, 1),
			new PieceSquare(1, 1),
			new PieceSquare(2, 1),
			new PieceSquare(2, 0),
			new PieceSquare(0, 2),
		},
		{	// 30
			new PieceSquare(0, 0),
			new PieceSquare(0, 1),
			new PieceSquare(1, 1),
			new PieceSquare(2, 1),
			new PieceSquare(2, 0),
			new PieceSquare(1, 2),
		},
		{	// 31
			new PieceSquare(2, 0),
			new PieceSquare(1, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
		},
		{	// 32
			new PieceSquare(0, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(2, 2),
		},
		{	// 33
			new PieceSquare(1, 0),
			new PieceSquare(2, 1),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
		},
		{	// 34
			new PieceSquare(2, 0),
			new PieceSquare(2, 1),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
		},
		{	// 35
			new PieceSquare(2, 0),
			new PieceSquare(2, 1),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(0, 2),		
			new PieceSquare(0, 3),
		}	
	};
	
	public static final Color colors[] = new Color[]{
			new Color(250, 2, 2),
			new Color(36, 217, 18),
			new Color(67, 60, 166),
			new Color(101, 255, 0),
			new Color(229, 68, 236),
			new Color(255, 39, 212),
			new Color(255, 173, 0),
			new Color(254, 19, 0),
			new Color(218, 112, 26),
			new Color(1, 42, 255),
			new Color(138, 58, 31),
			new Color(193, 53, 188),
			new Color(255, 199, 78),
			new Color(170, 170, 220),
			new Color(241, 202, 47),
			new Color(55, 144, 54),
			new Color(59, 211, 212),
			new Color(143, 20, 173), 
			new Color(71, 115, 56),
			new Color(212, 59, 199),
			new Color(130, 177, 37),
			new Color(135, 57, 35),
			new Color(20, 173, 49),
			new Color(170, 170, 222),
			new Color(127, 0, 178),
			new Color(57, 199, 53),
			new Color(130, 33, 192),
			new Color(170, 170, 170),
			new Color(254, 250, 71),
			new Color(255, 139, 70),
			new Color(171, 221, 170),
			new Color(255, 162, 0),
			new Color(43, 44, 188),
			new Color(230, 230, 230),
			new Color(189, 23, 23)
		};
	

	public static final Piece pieces[] = new Piece[]{
		new Piece(0, pieceSquares[0], null),
		new Piece(1, pieceSquares[1], null),
		new Piece(2, pieceSquares[2], null),
		new Piece(3, pieceSquares[3], null),
		new Piece(4, pieceSquares[4], null),
		new Piece(5, pieceSquares[5], null),
		new Piece(6, pieceSquares[6], null),
		new Piece(7, pieceSquares[7], null),
		new Piece(8, pieceSquares[8], null),
		new Piece(9, pieceSquares[9], null),
		new Piece(10, pieceSquares[10], null),
		new Piece(11, pieceSquares[11], null),
		new Piece(12, pieceSquares[12], null),
		new Piece(13, pieceSquares[13], null),
		new Piece(14, pieceSquares[14], null),
		new Piece(15, pieceSquares[15], null),
		new Piece(16, pieceSquares[16], null),
		new Piece(17, pieceSquares[17], null),
		new Piece(18, pieceSquares[18], null),
		new Piece(19, pieceSquares[19], null),
		new Piece(20, pieceSquares[20], null),
		new Piece(21, pieceSquares[21], null),
		new Piece(22, pieceSquares[22], null),
		new Piece(23, pieceSquares[23], null),
		new Piece(24, pieceSquares[24], null),
		new Piece(25, pieceSquares[25], null),
		new Piece(26, pieceSquares[26], null),
		new Piece(27, pieceSquares[27], null),
		new Piece(28, pieceSquares[28], null),
		new Piece(29, pieceSquares[29], null),
		new Piece(30, pieceSquares[30], null),
		new Piece(31, pieceSquares[31], null),
		new Piece(32, pieceSquares[32], null),
		new Piece(33, pieceSquares[33], null),
		new Piece(34, pieceSquares[34], null)	
	};
	
}