package com.halaesus.kabasuji.utils;

import com.halaesus.kabasuji.player.entity.Piece;
import com.halaesus.kabasuji.player.entity.PieceSquare;

public class PieceGenerator {

	//Note: Only correctly defined the first 18 hexominoes
	private static PieceSquare pieceSquares[][] = new PieceSquare[][]{
		{	// 1
			new PieceSquare(0, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
			new PieceSquare(0, 4),
			new PieceSquare(0, 5),
		},
		{	// 2
			new PieceSquare(0, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
			new PieceSquare(0, 4),
			new PieceSquare(1, 0),
		},
		{	// 3
			new PieceSquare(0, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
			new PieceSquare(0, 4),
			new PieceSquare(1, 1),
		},
		{	// 4
			new PieceSquare(0, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
			new PieceSquare(0, 4),
			new PieceSquare(1, 2),
		},
		{	// 5
			new PieceSquare(1, 0),
			new PieceSquare(1, 1),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
			new PieceSquare(0, 4),
		},
		{	// 6
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(1, 0),
			new PieceSquare(1, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
		},
		{	// 7
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(2, 2),
			new PieceSquare(0, 3),
		},
		{	// 8
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
			new PieceSquare(1, 3),
		},
		{	// 9
			new PieceSquare(0, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
		},
		{	// 10
			new PieceSquare(0, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
		},
		{	// 11
			new PieceSquare(0, 0),
			new PieceSquare(0, 1),
			new PieceSquare(0, 2),
			new PieceSquare(0, 3),
			new PieceSquare(1, 1),
			new PieceSquare(2, 1),
		},
		{	// 12
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
		},
		{	// 13
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(0, 1),
			new PieceSquare(1, 3),
		},
		{	// 14
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(0, 2),
			new PieceSquare(1, 3),
		},
		{	// 15
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(0, 3),
			new PieceSquare(1, 3),
		},
		{	// 16
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 2),
			new PieceSquare(1, 2),
			new PieceSquare(0, 2),
			new PieceSquare(1, 3),
		},
		{	// 17
			new PieceSquare(1, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
			new PieceSquare(0, 1),
			new PieceSquare(2, 1),
		},
		{	// 18 // 
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
		},
		{	// 19
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
		},
		{	// 20
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
		},
		{	// 21
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
		},
		{	// 22
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
		},
		{	// 23
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
		},
		{	// 24
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
		},
		{	// 25
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
		},
		{	// 26
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
		},
		{	// 27
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
		},
		{	// 28
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
		},
		{	// 29
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
		},
		{	// 30
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
		},
		{	// 31
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
		},
		{	// 32
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
		},
		{	// 33
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
		},
		{	// 34
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
		},
		{	// 35
			new PieceSquare(0, 0),
			new PieceSquare(1, 0),
			new PieceSquare(2, 0),
			new PieceSquare(1, 1),
			new PieceSquare(1, 2),
			new PieceSquare(1, 3),
		}	
	};
	

	public static final Piece pieces[] = new Piece[]{
		new Piece(0,0,0, pieceSquares[0]),
		new Piece(0,0,0, pieceSquares[1]),
		new Piece(0,0,0, pieceSquares[2]),
		new Piece(0,0,0, pieceSquares[3]),
		new Piece(0,0,0, pieceSquares[4]),
		new Piece(0,0,0, pieceSquares[5]),
		new Piece(0,0,0, pieceSquares[6]),
		new Piece(0,0,0, pieceSquares[7]),
		new Piece(0,0,0, pieceSquares[8]),
		new Piece(0,0,0, pieceSquares[9]),
		new Piece(0,0,0, pieceSquares[10]),
		new Piece(0,0,0, pieceSquares[11]),
		new Piece(0,0,0, pieceSquares[12]),
		new Piece(0,0,0, pieceSquares[13]),
		new Piece(0,0,0, pieceSquares[14]),
		new Piece(0,0,0, pieceSquares[15]),
		new Piece(0,0,0, pieceSquares[16]),
		new Piece(0,0,0, pieceSquares[17]),
		new Piece(0,0,0, pieceSquares[18]),
		new Piece(0,0,0, pieceSquares[19]),
		new Piece(0,0,0, pieceSquares[20]),
		new Piece(0,0,0, pieceSquares[21]),
		new Piece(0,0,0, pieceSquares[22]),
		new Piece(0,0,0, pieceSquares[23]),
		new Piece(0,0,0, pieceSquares[24]),
		new Piece(0,0,0, pieceSquares[25]),
		new Piece(0,0,0, pieceSquares[26]),
		new Piece(0,0,0, pieceSquares[27]),
		new Piece(0,0,0, pieceSquares[28]),
		new Piece(0,0,0, pieceSquares[29]),
		new Piece(0,0,0, pieceSquares[30]),
		new Piece(0,0,0, pieceSquares[31]),
		new Piece(0,0,0, pieceSquares[32]),
		new Piece(0,0,0, pieceSquares[33]),
		new Piece(0,0,0, pieceSquares[34])	
	};
	
}